ARG MONGO_VERSION=4.0.10
FROM mongo:$MONGO_VERSION
COPY scripts/ /scripts/
RUN apt-get update && apt-get install -y \
  nmap \
  dos2unix && dos2unix scripts/**
LABEL version=$MONGO_VERSION
EXPOSE 27017