spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://mongo1:50001,mongo2:50002,mongo3:50003/test?replicaSet=docker-rs

logging:
  path: logs
  file:
    max-size: 20MB
    max-history: 10

storage:
  bulk-upload-path: uploads/files